[alias]
blinky = "run --release --target riscv32imac-unknown-none-elf --no-default-features"
blinky-check = "check --release --target riscv32imac-unknown-none-elf --no-default-features"
blinky-build = "build --release --target riscv32imac-unknown-none-elf --no-default-features"
blinky-s3 = "run --release --target xtensa-esp32s3-none-elf --no-default-features"
blinky-s3-check = "check --release --target xtensa-esp32s3-none-elf --no-default-features"
blinky-s3-build = "build --release --target xtensa-esp32s3-none-elf --no-default-features"

[target.riscv32imac-unknown-none-elf]
runner = "espflash flash --monitor"
rustflags = [
  "-C",
  "link-arg=-Tlinkall.x",
]

[target.xtensa-esp32s3-none-elf]
runner = "espflash flash --monitor"
rustflags = [
  "-C",
  "link-arg=-Tlinkall.x",
]

[build]
target = "riscv32imac-unknown-none-elf"
