// @generated by cargo xtask generate-board-examples
//!
//! Wiring:
//! SOS blinky for `generic` (ESP32).
//!
//! Setup:
//! - Wire an external plain LED as active-high.
//! - LED anode (long leg) -> resistor -> GPIO0
//! - LED cathode (short leg) -> GND

#![no_std]
#![no_main]

use core::{convert::Infallible, future::pending};
use embassy_executor::Spawner;
use embassy_time::Duration;
use esp_backtrace as _;
use log::info;

use device_envoy_esp::{
    Result, init_and_start, led,
    led::{Led as _, LedLevel, OnLevel},
};

esp_bootloader_esp_idf::esp_app_desc!();

const LED_ON_LEVEL: OnLevel = OnLevel::High;

const DOT_MS: u64 = 200;
const DASH_MS: u64 = DOT_MS * 3;
const SYMBOL_GAP_MS: u64 = DOT_MS;
const LETTER_GAP_MS: u64 = DOT_MS * 3;
const WORD_GAP_MS: u64 = DOT_MS * 7;

const DOT_DURATION: Duration = Duration::from_millis(DOT_MS);
const DASH_DURATION: Duration = Duration::from_millis(DASH_MS);
const SYMBOL_GAP: Duration = Duration::from_millis(SYMBOL_GAP_MS);
const LETTER_GAP: Duration = Duration::from_millis(LETTER_GAP_MS);
const WORD_GAP: Duration = Duration::from_millis(WORD_GAP_MS);

const SOS: [(LedLevel, Duration); 18] = [
    (LedLevel::On, DOT_DURATION),
    (LedLevel::Off, SYMBOL_GAP),
    (LedLevel::On, DOT_DURATION),
    (LedLevel::Off, SYMBOL_GAP),
    (LedLevel::On, DOT_DURATION),
    (LedLevel::Off, LETTER_GAP),
    (LedLevel::On, DASH_DURATION),
    (LedLevel::Off, SYMBOL_GAP),
    (LedLevel::On, DASH_DURATION),
    (LedLevel::Off, SYMBOL_GAP),
    (LedLevel::On, DASH_DURATION),
    (LedLevel::Off, LETTER_GAP),
    (LedLevel::On, DOT_DURATION),
    (LedLevel::Off, SYMBOL_GAP),
    (LedLevel::On, DOT_DURATION),
    (LedLevel::Off, SYMBOL_GAP),
    (LedLevel::On, DOT_DURATION),
    (LedLevel::Off, WORD_GAP),
];

led! {
    SosLed {
        pin: GPIO0,
        max_steps: 20,
    }
}

#[esp_rtos::main]
async fn main(spawner: Spawner) -> ! {
    let err = inner_main(spawner).await.unwrap_err();
    panic!("{err:?}");
}

async fn inner_main(spawner: Spawner) -> Result<Infallible> {
    init_and_start!(p);

    esp_println::logger::init_logger(log::LevelFilter::Info);
    info!("SOS plain LED blinky starting on GPIO0 (generic)");

    let sos_led = SosLed::new(p.GPIO0, LED_ON_LEVEL, spawner)?;
    sos_led.animate(SOS);

    pending().await
}
